version: '3.3'

services:
  speedtest:
    build: ./
    expose:
      - 8000
    volumes:
      - ./app:/app/app
  nginx:
    build: nginx/
    ports:
      - 3010:80
    volumes:
      - ./app/static:/app/static
